Create npm-publish.yml
wiremock/wiremock-testcontainers-node pull request #7
Opened 2023-10-26 15:11 UTC by kurayami07734

adding github action for automating npm publish

## Need
- [ ] npm auth token

2023-10-28 21:13 UTC, oleg-nenashev approved these changes
LGTM

2023-10-29 13:36 UTC, kurayami07734 commented
Closes #5

@oleg-nenashev we need to setup npm access token as actions secret for this action to work

2023-10-29 15:48 UTC, oleg-nenashev commented
@kurayami07734 Deploy tokens are associated to users, so normally you should be able to add one. I will double-check what happens there. Please also add the organization scope (`@wiremock`) to the metadata: https://docs.npmjs.com/about-organization-scopes-and-packages

2023-10-29 15:51 UTC, oleg-nenashev commented on .github/workflows/npm-publish.yml
> +          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
The token is now configured

```suggestion
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
```

2023-10-29 16:12 UTC, oleg-nenashev requested changes
Requesting changes to indicate an update is needed before the merge

2023-10-29 16:43 UTC, oleg-nenashev approved these changes

2023-10-29 17:02 UTC, merged